FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        pkg-config \
        libc-dev \
        g++ \
        make \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY eh_requirements.txt .
RUN pip install --no-cache-dir -r eh_requirements.txt

COPY ./src/init_db.py ./src/event*.py ./

CMD ["python", "event_handler.py"]
