FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y tor && apt-get clean

RUN mkdir -p /var/lib/tor/hidden_service /etc/tor

COPY ./tor/torrc /etc/tor/torrc

RUN chown -R debian-tor:debian-tor /var/lib/tor/hidden_service

EXPOSE 80

CMD ["tor", "-f", "/etc/tor/torrc"]
