FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    libsecp256k1-dev \
    && rm -rf /var/lib/apt/lists/*

COPY up_requirements.txt .

RUN pip install --no-cache-dir -r up_requirements.txt

COPY ./src/updater.py ./

EXPOSE 8000

CMD ["uvicorn", "updater:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
