FROM python:3.11-alpine

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        pkg-config \
        libc-dev \
        g++ \
        make \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY eh_requirements.txt .
RUN pip install --no-cache-dir -r eh_requirements.txt

COPY ./python_stuff/event*.py .
CMD [ "python", "event_handler.py"]

