FROM python:3.10
WORKDIR /app

COPY nq_requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r nq_requirements.txt

COPY ./python_stuff/nost_query.py .

CMD ["python", "nost_query.py"]
